#!/usr/bin/env python
from __future__ import print_function
import json
import math
import subprocess
import time
import os.path
import sys

if sys.version_info[0] < 3:
    import urllib2 as request
else:
    import urllib.request as request


PAGE_SIZE = 100
TERM = "language:openscad"


def query(term, page):
    url = "https://api.github.com/search/repositories?q={}&page={}&per_page={}".format(
        term, page, PAGE_SIZE
    )
    data = request.urlopen(url).read().decode("utf-8")
    return json.loads(data)


print('searching github for "{}"'.format(TERM))
data = query(TERM, page=1)
items = data["items"]

total = data["total_count"]
pages = int(math.ceil(total / PAGE_SIZE))

for n in range(2, pages + 2):
    time.sleep(0.1)
    data = query(TERM, page=n)
    items += data["items"]

print("found {} repositories".format(len(items)))

for i, item in enumerate(items[1:]):
    name = item["full_name"]
    folder = os.path.join("test-repos", name)
    if not os.path.exists(folder):
        print("cloning {}".format(name))
        cmd = ["git", "clone", "--depth=1", item["html_url"], folder]
        subprocess.call(cmd)
